version: "3.1"

services:
  spk_cli:
    image: mkenjis/ubspkcli_yarn_img
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst
      
  hive:
    image: mkenjis/ubhive_img
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst

  mysql:
    image: mysql:5.7
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=admsys123
      - MYSQL_DATABASE=metastore
      - MYSQL_USER=hiveuser
      - MYSQL_PASSWORD=hive123
    volumes:
      - .:/root/staging
      - db:/var/lib/mysql

networks:
  mynet:
    external:
       name: mynet

volumes:
  db:
